# Generated by Django 5.2.7 on 2025-11-14 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courts',
            fields=[
                ('court_id', models.AutoField(primary_key=True, serialize=False)),
                ('court_name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourtSlots',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courts')),
            ],
        ),
        migrations.CreateModel(
            name='CourtBookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courts')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courtslots')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('court', 'slot', 'status'), name='unique_booking')],
            },
        ),
    ]
