# Generated by Django 5.2.8 on 2025-11-17 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_courtbookings_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtslots',
            name='court',
        ),
        migrations.AlterField(
            model_name='courts',
            name='court_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courts',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='courts',
            name='location',
            field=models.CharField(default='Fast Nuces', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courts',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CourtBookings',
        ),
        migrations.DeleteModel(
            name='CourtSlots',
        ),
    ]
