# Generated by Django 5.2.8 on 2025-11-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_booking_options_booking_status_and_more'),
        ('core', '0006_booking_status'),
    ]

    operations = [
    ]
