# Generated by Django 5.2.8 on 2025-11-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20251119_0334'),
        ('core', '0007_merge_20251119_2107'),
    ]

    operations = [
    ]
