# Generated by Django 5.2.7 on 2025-11-21 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20251119_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='sport_name',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='team_based',
        ),
        migrations.AddField(
            model_name='sport',
            name='max_players',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='sport',
            name='min_players',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sport',
            name='sports_name',
            field=models.CharField(default='Unknown Sport', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='status',
            field=models.CharField(choices=[('General', 'General'), ('Esports', 'Esports'), ('Sports', 'Sports')], default='Sports', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courts'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
