# Generated by Django 5.2.7 on 2025-11-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_sport_event_type_remove_sport_sport_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='core.sport')),
            ],
        ),
    ]
