# Generated by Django 5.2.7 on 2025-11-22 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sportregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='bio',
        ),
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport')),
                ('sport_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sportregistration')),
            ],
        ),
        migrations.CreateModel(
            name='OlympiadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.teamregistration')),
            ],
        ),
    ]
