# Generated by Django 5.2.8 on 2025-11-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_player_bio_teamregistration_olympiadplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('round', models.CharField(choices=[('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final')], max_length=50)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('score_team1', models.IntegerField(blank=True, null=True)),
                ('score_team2', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='core.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='core.team')),
            ],
        ),
    ]
