# Generated by Django 5.2.8 on 2025-11-22 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event_type',
            field=models.CharField(choices=[('LOG', 'LOG'), ('OLYMPIAD', 'OLYMPIAD')], default='LOG', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='olympiad_team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_team1_matches', to='core.teamregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='olympiad_team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olympiad_team2_matches', to='core.teamregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='olympiad_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiad_won_matches', to='core.teamregistration'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_matches', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_matches', to='core.team'),
        ),
    ]
