# Generated by Django 5.2.8 on 2025-11-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_match_event_type_match_olympiad_team1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='olympiad_winner',
            new_name='olympiad_match_winner',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='sport_registration',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='total_fee',
        ),
        migrations.AlterField(
            model_name='match',
            name='event_type',
            field=models.CharField(choices=[('LOG', 'LOG'), ('OLYMPIAD', 'OLYMPIAD')], default='OLYMPIAD', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(choices=[('knockout', 'Knockout'), ('round_robin', 'Round Robin'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='event_type',
            field=models.CharField(choices=[('LOG', 'LOG')], max_length=20),
        ),
    ]
