# Generated by Django 5.2.8 on 2025-11-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_olympiad_winner_match_olympiad_match_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
