# Generated by Django 5.2.8 on 2025-11-23 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification_housecaptain_houseproposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseproposal',
            name='sports_captains',
        ),
        migrations.CreateModel(
            name='SportCaptainDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('roll_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_captains', to='core.houseproposal')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport')),
            ],
            options={
                'unique_together': {('proposal', 'sport')},
            },
        ),
    ]
