# Generated by Django 5.2.8 on 2025-11-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_houseproposal_sports_captains_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='is_availableinLog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sport',
            name='is_availableinOlympiad',
            field=models.BooleanField(default=True),
        ),
    ]
