# Generated by Django 5.2.8 on 2025-11-23 20:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sport_is_availableinlog_sport_is_availableinolympiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='pick_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='picked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('current_round', models.IntegerField(default=1)),
                ('current_pick_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sport')),
            ],
            options={
                'unique_together': {('sport',)},
            },
        ),
    ]
