# Generated by Django 5.2.8 on 2025-11-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_draftpick_pick_order_draftpick_picked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_proposals_open', models.BooleanField(default=False, help_text='Allow users to propose new houses')),
                ('player_registration_open', models.BooleanField(default=False, help_text='Allow players to register for sports')),
                ('houses_finalized', models.BooleanField(default=False, help_text='Houses have been finalized, no more proposals')),
                ('registration_finalized', models.BooleanField(default=False, help_text='Player registrations finalized, no more registrations')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LOG Module Settings',
                'verbose_name_plural': 'LOG Module Settings',
            },
        ),
    ]
