# Generated by Django 5.2.8 on 2025-11-25 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_logmodulesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('house_a_score', models.IntegerField(blank=True, null=True)),
                ('house_b_score', models.IntegerField(blank=True, null=True)),
                ('is_draw', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_matches_created', to=settings.AUTH_USER_MODEL)),
                ('house_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_matches_as_a', to='core.house')),
                ('house_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_matches_as_b', to='core.house')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_matches', to='core.sport')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_matches_as_team_a', to='core.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_matches_as_team_b', to='core.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_matches_won', to='core.house')),
            ],
            options={
                'verbose_name': 'LOG Match',
                'verbose_name_plural': 'LOG Matches',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='LogLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_leaderboard_entries', to='core.house')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_leaderboard_entries', to='core.sport')),
            ],
            options={
                'verbose_name': 'LOG Leaderboard Entry',
                'verbose_name_plural': 'LOG Leaderboard',
                'ordering': ['-points', '-goal_difference', '-goals_for'],
                'unique_together': {('house', 'sport')},
            },
        ),
    ]
