# Generated by Django 5.2.7 on 2025-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_logmatch_logleaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmatch',
            name='house_a_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logmatch',
            name='house_b_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
