# Generated by Django 5.2.7 on 2025-11-25 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_logmatch_house_a_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_concluded', models.BooleanField(default=False)),
                ('concluded_at', models.DateTimeField(blank=True, null=True)),
                ('final_standings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_championships', to='core.house')),
                ('concluded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_conclusions', to=settings.AUTH_USER_MODEL)),
                ('runner_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_runnerups', to='core.house')),
            ],
            options={
                'verbose_name': 'LOG Conclusion',
                'verbose_name_plural': 'LOG Conclusions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogSportWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tie', models.BooleanField(default=False)),
                ('manually_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_sport_winner', to='core.sport')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_sports_won', to='core.house')),
            ],
            options={
                'verbose_name': 'LOG Sport Winner',
                'verbose_name_plural': 'LOG Sport Winners',
            },
        ),
    ]
