# Generated by Django 5.2.8 on 2025-11-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_logconclusion_logsportwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.BooleanField(default=False, help_text='Allow teams to register for Olympiad')),
            ],
            options={
                'verbose_name': 'Olympiad Settings',
                'verbose_name_plural': 'Olympiad Settings',
            },
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
